- hosts: vm
  vars_files:
    - 'vars/lisp.var'

  tasks:

    - name: Download quicklisp.lisp
      command: curl -o {{ql_file}} {{ql_url}} creates={{qlfile}}

    - name: Install Quicklisp
      command: {{lisp}} --load {{ql_file}}
               --eval '(quicklisp-quickstart:install)' --quit
